/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p dbussrc/statusnotifierwatcher StatusNotifierWatcher.xml org.kde.StatusNotifierWatcher
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "statusnotifierwatcher.h"

/*
 * Implementation of interface class OrgKdeStatusNotifierWatcherInterface
 */

OrgKdeStatusNotifierWatcherInterface::OrgKdeStatusNotifierWatcherInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeStatusNotifierWatcherInterface::~OrgKdeStatusNotifierWatcherInterface()
{
}

