######################################################################
# Automatically generated by qmake (2.01a) ?? 21. ??? 23:34:31 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS = libqutim \
		  src

CONFIG += ordered
