#ifndef VKONTAKTE_GLOBAL_H
#define VKONTAKTE_GLOBAL_H


#include <QIcon>
#include <QtCore>

#if defined(VKONTAKTE_LIBRARY)
#  define VKONTAKTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VKONTAKTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VKONTAKTE_GLOBAL_H
