#cmakedefine HAVE_ZLIB
#cmakedefine HAVE_GNUTLS
#cmakedefine HAVE_OPENSSL
#cmakedefine HAVE_LIBIDN
#cmakedefine HAVE_ARPA_NAMESER_H
#cmakedefine HAVE_DLFCN_H
#cmakedefine HAVE_DN_SKIPNAME
#cmakedefine HAVE_ERRNO_H
#cmakedefine HAVE_GETADDRINFO
#cmakedefine HAVE_INTTYPES_H
#cmakedefine HAVE_LIBBIND
#cmakedefine HAVE_LIBRESOLV
#cmakedefine HAVE_LIBSOCKET
#cmakedefine HAVE_MEMORY_H
#cmakedefine HAVE_PTHREAD
#cmakedefine HAVE_RES_QUERY
#cmakedefine HAVE_RES_QUERYDOMAIN
#cmakedefine HAVE_SETSOCKOPT
#cmakedefine HAVE_STDINT_H
#cmakedefine HAVE_STDLIB_H
#cmakedefine HAVE_STRINGS_H
#cmakedefine HAVE_STRING_H
#cmakedefine HAVE_SYS_STAT_H
#cmakedefine HAVE_SYS_TYPES_H
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_STDC_HEADERS
