BUILD_DIR="../build/release"
SOURCE_DIR="${PWD}"

FLAGS="-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=../../dist/release \
	-DWITH_DOXYGEN=0
	-DHUMANITY-ICONS=0 \
	-DJREEN_USE_SIMPLESASL=1 \
	-DOSCAR_USE_3RDPARTY_HMAC=1 \
	-DQUTIM_INSTALL_ICON_THEME=1 \
	-DTRAYICON=0 \
	-DSIMPLECONTACTLISTWIDGET=0 \
	-DTORYCONTACTLISTWIDGET=0 \
	-DIDLEDETECTOR=0 \
	-DQRCICONS=0 \
	-DANTIBOSS=0 \
	-DUNITYLAUNCHER=0 \
	-DAWN=0
	"

mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}
echo "Build qutIM release"
cmake ${SOURCE_DIR} ${FLAGS}
make install
