$BUILD_DIR="${PWD}/../build/release"
$SOURCE_DIR="${PWD}"
$INSTALL_DIR="../../dist/release"
$BUILD_TYPE="Release"

$FLAGS="-DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
	-DCMAKE_INSTALL_PREFIX='${INSTALL_DIR}'
	-DWITH_DOXYGEN=0
	-DHUMANITY-ICONS=0 
	-DJREEN_USE_SIMPLESASL=1 
	-DOSCAR_USE_3RDPARTY_HMAC=1 
	-DQUTIM_INSTALL_ICON_THEME=1 
	-DQRCICONS=0 
	-DQUTIM_CREATE_BUNDLE=1
	"

mkdir $BUILD_DIR
cd $BUILD_DIR
echo "cmake ${SOURCE_DIR} ${FLAGS}"
cmake ${SOURCE_DIR} ${FLAGS}
nmake install
cd $SOURCE_DIR