FIND_PATH( HWRMVIBRA_INCLUDE_DIR hwrmvibra.h )
FIND_LIBRARY( HWRMVIBRA_LIBRARIES hwrmvibraclient )

if( HWRMVIBRA_LIBRARIES AND HWRMVIBRA_INCLUDE_DIR )
	message( STATUS "Found hwrmvibra: ${HWRMVIBRA_LIBRARIES}" )
	set( HWRMVIBRA_FOUND true )
else( HWRMVIBRA_LIBRARIES AND HWRMVIBRA_INCLUDE_DIR )
	message( STATUS "Could NOT find hwrmvibra" )
endif( HWRMVIBRA_LIBRARIES AND HWRMVIBRA_INCLUDE_DIR )
