#ifndef SIMPLECONTACTLIST_GLOBAL_H
#define SIMPLECONTACTLIST_GLOBAL_H

#if defined(SIMPLECONTACTLIST_LIBRARY)
#  define SIMPLECONTACTLIST_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLECONTACTLIST_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLECONTACTLIST_GLOBAL_H
