#ifndef CHATLAYER_GLOBAL_H
#define CHATLAYER_GLOBAL_H

#if defined(ADIUMCHAT_LIBRARY)
#  define ADIUMCHAT_EXPORT Q_DECL_EXPORT
#else
#  define ADIUMCHAT_EXPORT Q_DECL_IMPORT
#endif

#endif // CHATLAYER_GLOBAL_H
