FIND_PATH(APILAYER_INCLUDE_DIR "qw7apiwrapper/")
FIND_LIBRARY(APILAYER_LIBRARIES w7apiqtwrapper)

if(APILAYER_LIBRARIES AND APILAYER_INCLUDE_DIR)
	message( STATUS "Found ApiLayer: ${APILAYER_LIBRARIES}")
	set( APILAYER_FOUND 1)
else(APILAYER_LIBRARIES AND APILAYER_INCLUDE_DIR)
	message( STATUS "Could NOT find ApiLayer")
endif(APILAYER_LIBRARIES AND APILAYER_INCLUDE_DIR)
